### PR TITLE
Add an option to override Swift endpoint URL

### LINKED ISSUE #50: Add an ability to override swift endpoint URL
Swift supports ACLs (https://docs.openstack.org/swift/latest/overview_acl.html) and it is possible to grant an access to http://swift/v1/AUTH_project1/container1 for a user that has a project2 scope token, e.g.
```
.r:*,.rlistings,user2:project2
```

By default gophercloud extracts the endpoint URL using the token catalog:

```
curl -s http://identity/v3/auth/tokens -H "Content-Type: application/json" -d'AUTH_PARAMS'| jq -r '.token.catalog[]|select(.type=="object-store")|.endpoints[]|select(.interface=="public")'
{
  "id": "project2",
  "interface": "public",
  "region_id": "region1",
  "url": "http://swift/v1/AUTH_project2",
  "region": "region1"
}
```

In order to override the default catalog URL, gophercloud supports specifying the custom `Endpoint` for the `ServiceClient`.

It'd be great to have a custom URL or custom projectID option for openstack velero project.

### PR DESCRIPTION
**Pull request by kayrus**
Fixes #50

### CODE REVIEW

**Comment by Lirt** [comment]
Hi, thank you for PR. I think it looks good. 

Can you please rebase on master? I updated CI to run tests on PRs https://github.com/Lirt/velero-plugin-for-openstack/pull/52.

Maybe we can also add a small test for `ReplaceAccount()` function.

**Comment by kayrus** [comment]
@Lirt done

**Comment by Lirt** [comment]
Hi @kayrus,

I added [one commit with tests](https://github.com/Lirt/velero-plugin-for-openstack/pull/51/commits/cd7487c9471ea1410e04cbca5815b7e2ccf422e2) - I hope it's OK (if not you can remove it and do by yourself). If yes, please check if those tests make sense or update them.

I think the change is good overall and we can merge it you're fine with it.

I will add update versions afterwards and release as v0.5.0. I don't yet have [release process in CI](https://github.com/Lirt/velero-plugin-for-openstack/issues/36) (will try to add it soon), so I'll need to do it manually.

**Comment by kayrus** [comment]
Thanks. Tests are fine with me.
As for the clouds.yaml, the endpoint override must be implemented in gophercloud/utils first. And at first glance it's not so trivial as it looks like.

**Comment by kayrus** [comment]
Oh. One more thing. Could you please replace a `bucket` term with a `container`? Logs that contain `bucket` term confuse with S3 buckets.

**Comment by Lirt** [comment]
>  As for the clouds.yaml, the endpoint override must be implemented in gophercloud/utils first. And at first glance it's not so trivial as it looks like.

Hi again, so for now can we skip `clouds.yaml` integration and merge as it is?

**Comment by kayrus** [comment]
Yes, for now I think we can skip `clouds.yaml`.

**Comment by kayrus** [comment]
Thanks. When can I expect a new release?

**Comment by Lirt** [comment]
I just released it :tada:.

**Pull request merged**
