### PR TITLE
Add support for static storage container name

### PR DESCRIPTION
**Pull request by Jonher937**
When using a storage backend such as ceph block, the `container` corresponds to a `ceph pool` and is not managed by the user, but rather by the storage/Openstack operator.

In a S3 deployment it's fine for this to be dynamic as it's managed by the user, but in some cases (such as ceph block) the user needs to be able to override this `container` value.

With this change I was able to point to our `backups` pools, same pool as what Openstack Cinder Backup is using.

### CODE REVIEW

**Comment by Lirt** [comment]
Hello @Jonher937,

That sounds good. Give me some time to run quick test and reach back to you.

**Comment by Lirt** [comment]
Hey, I released [fix for CI](https://github.com/Lirt/velero-plugin-for-openstack/pull/108) and synced this branch.

If the CI runs fine I can merge the PR.

**Comment by Jonher937** [comment]
Thanks for the quick merge and maintaining this plugin :star:

**Comment by Lirt** [comment]
Thank you for contribution. 

New tag was published successfully.

**Pull request merged**
