### PR TITLE
Bump Gophercloud to the latest greatest v2

### PR DESCRIPTION
**Pull request by EmilienM**
This PR bumps the Gophercloud library so you have the latest greates from it.

2 commits: the bump and the code changes needed for v2, all minor.

- **[vendoring] bump gophercloud to v2**
- **Code changes for Gophercloud v2**

### CODE REVIEW

**Comment by EmilienM** [comment]
cc @Lirt

**Comment by Lirt** [comment]
Hello @EmilienM,

thank you for generous contribution. 

I will fully look into it in the next days but I had a quick look around and I see that you committed `/vendor` directory. Is this somehow important to be added in this project? We have a very simple dependency list and I don't understand what is this supposed to solve or improve.

**Comment by EmilienM** [comment]
> thank you for generous contribution.

My pleasure. Just so you know, I'm a Gophercloud maintainer and a Red Hat employee who is interested to add this plugin into our downstream product.

> I will fully look into it in the next days but I had a quick look around and I see that you committed `/vendor` directory. Is this somehow important to be added in this project? We have a very simple dependency list and I don't understand what is this supposed to solve or improve.

I didn't realize you were not vendoring :man_facepalming: . I removed the directory.
Thanks

**Comment by Lirt** [comment]
:smiley: That's fine.

I remember you from my devstack-action PR :+1:.

**Comment by Lirt** [comment]
I see that we also need to bump go version in CI, can you please change it?
- .github/workflows/tests.yaml
- docker/Dockerfile

I will need to spend some time bumping CI deps later on.

**Comment by Lirt** [comment]
Everything looks good.

Thank you for contribution :pray: .

**Pull request merged**
