### PR TITLE
Set proper package name

### LINKED ISSUE #74: [FEAT] Change go package name
**Is your feature request related to a problem? Please describe.**

No problems, just confusing package name.

**Describe the solution you'd like**

Change package name:

```diff
diff --git a/go.mod b/go.mod
index 28c5e99..e0a50a8 100644
--- a/go.mod
+++ b/go.mod
@@ -1,4 +1,4 @@
-module github.com/Lirt/velero-plugin-swift
+module github.com/Lirt/velero-plugin-for-openstack
 
 go 1.19
 
```

This fix is required for a proper user agent version in #75

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #74

### CODE REVIEW

**Comment by kayrus** [comment]
@Lirt ready for review

**Review by Lirt — APPROVED** [review]
lgtm

**Comment by Lirt** [comment]
Hi,
Is this MR OK to be merged as first? Probably followed by this small MR - https://github.com/Lirt/velero-plugin-for-openstack/pull/76/files?

**Comment by kayrus** [comment]
The sequence doesn't really matter :)

**Pull request merged**
